"""provider column

Revision ID: f5c19dfe83c6
Revises: aa63d5a87185
Create Date: 2022-05-19 01:17:40.106393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c19dfe83c6'
down_revision = 'aa63d5a87185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('provider', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'provider')
    op.drop_column('reviews', 'content')
    # ### end Alembic commands ###
